#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC =
CFLAGS = -Wall
RESINC =
LIBDIR =
LIB =
LDFLAGS =

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
CFLAGS_SDL_RELEASE = $(CFLAGS_DEBUG) -DUSING_SDL
CFLAGS_CONSOLE_RELEASE = $(CFLAGS_RELEASE) -DUSING_CONSOLE
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LIB_SDL_RELEASE = $(LIB) -lSDLmain -lSDL -lSDL_image -lSDL_ttf
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_CONSOLE_RELEASE = obj/Release/console
OBJDIR_SDL_RELEASE = obj/Release/sdl
DEP_RELEASE =
OUT_SDL_RELEASE = sudoku_gui
OUT_CONSOLE_RELEASE = sudoku_cli

OBJ_SDL_RELEASE = $(OBJDIR_SDL_RELEASE)/src/SDLgame.o $(OBJDIR_SDL_RELEASE)/src/SDLmain.o $(OBJDIR_SDL_RELEASE)/src/game.o $(OBJDIR_SDL_RELEASE)/src/grid.o $(OBJDIR_SDL_RELEASE)/src/lib.o $(OBJDIR_SDL_RELEASE)/src/main.o $(OBJDIR_SDL_RELEASE)/src/save_load.o

OBJ_CONSOLE_RELEASE = $(OBJDIR_CONSOLE_RELEASE)/src/SDLgame.o $(OBJDIR_CONSOLE_RELEASE)/src/SDLmain.o $(OBJDIR_CONSOLE_RELEASE)/src/game.o $(OBJDIR_CONSOLE_RELEASE)/src/grid.o $(OBJDIR_CONSOLE_RELEASE)/src/lib.o $(OBJDIR_CONSOLE_RELEASE)/src/main.o $(OBJDIR_CONSOLE_RELEASE)/src/save_load.o

all: console sdl

console: console_release

sdl: sdl_release

clean: clean_release
	rm -rf obj

before_sdl_release:
	test -d Release || mkdir -p Release
	test -d $(OBJDIR_SDL_RELEASE) || mkdir -p $(OBJDIR_SDL_RELEASE)
	test -d $(OBJDIR_SDL_RELEASE)/src || mkdir -p $(OBJDIR_SDL_RELEASE)/src

before_console_release:
	test -d Release || mkdir -p Release
	test -d $(OBJDIR_CONSOLE_RELEASE) || mkdir -p $(OBJDIR_CONSOLE_RELEASE)
	test -d $(OBJDIR_CONSOLE_RELEASE)/src || mkdir -p $(OBJDIR_CONSOLE_RELEASE)/src

after_release:

sdl_release: before_sdl_release out_sdl_release after_release

console_release: before_console_release out_console_release after_release

out_sdl_release: before_sdl_release $(OBJ_SDL_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_SDL_RELEASE) $(OBJ_SDL_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_SDL_RELEASE)

out_console_release: before_console_release $(OBJ_CONSOLE_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_CONSOLE_RELEASE) $(OBJ_CONSOLE_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

#SDL release object files
$(OBJDIR_SDL_RELEASE)/src/SDLgame.o: src/SDLgame.c
	$(CC) $(CFLAGS_SDL_RELEASE) $(INC_RELEASE) -c src/SDLgame.c -o $(OBJDIR_SDL_RELEASE)/src/SDLgame.o

$(OBJDIR_SDL_RELEASE)/src/SDLmain.o: src/SDLmain.c
	$(CC) $(CFLAGS_SDL_RELEASE) $(INC_RELEASE) -c src/SDLmain.c -o $(OBJDIR_SDL_RELEASE)/src/SDLmain.o

$(OBJDIR_SDL_RELEASE)/src/game.o: src/game.c
	$(CC) $(CFLAGS_SDL_RELEASE) $(INC_RELEASE) -c src/game.c -o $(OBJDIR_SDL_RELEASE)/src/game.o

$(OBJDIR_SDL_RELEASE)/src/grid.o: src/grid.c
	$(CC) $(CFLAGS_SDL_RELEASE) $(INC_RELEASE) -c src/grid.c -o $(OBJDIR_SDL_RELEASE)/src/grid.o

$(OBJDIR_SDL_RELEASE)/src/lib.o: src/lib.c
	$(CC) $(CFLAGS_SDL_RELEASE) $(INC_RELEASE) -c src/lib.c -o $(OBJDIR_SDL_RELEASE)/src/lib.o

$(OBJDIR_SDL_RELEASE)/src/main.o: src/main.c
	$(CC) $(CFLAGS_SDL_RELEASE) $(INC_RELEASE) -c src/main.c -o $(OBJDIR_SDL_RELEASE)/src/main.o

$(OBJDIR_SDL_RELEASE)/src/save_load.o: src/save_load.c
	$(CC) $(CFLAGS_SDL_RELEASE) $(INC_RELEASE) -c src/save_load.c -o $(OBJDIR_SDL_RELEASE)/src/save_load.o


#Console release object files
$(OBJDIR_CONSOLE_RELEASE)/src/SDLgame.o: src/SDLgame.c
	$(CC) $(CFLAGS_CONSOLE_RELEASE) $(INC_RELEASE) -c src/SDLgame.c -o $(OBJDIR_CONSOLE_RELEASE)/src/SDLgame.o

$(OBJDIR_CONSOLE_RELEASE)/src/SDLmain.o: src/SDLmain.c
	$(CC) $(CFLAGS_CONSOLE_RELEASE) $(INC_RELEASE) -c src/SDLmain.c -o $(OBJDIR_CONSOLE_RELEASE)/src/SDLmain.o

$(OBJDIR_CONSOLE_RELEASE)/src/game.o: src/game.c
	$(CC) $(CFLAGS_CONSOLE_RELEASE) $(INC_RELEASE) -c src/game.c -o $(OBJDIR_CONSOLE_RELEASE)/src/game.o

$(OBJDIR_CONSOLE_RELEASE)/src/grid.o: src/grid.c
	$(CC) $(CFLAGS_CONSOLE_RELEASE) $(INC_RELEASE) -c src/grid.c -o $(OBJDIR_CONSOLE_RELEASE)/src/grid.o

$(OBJDIR_CONSOLE_RELEASE)/src/lib.o: src/lib.c
	$(CC) $(CFLAGS_CONSOLE_RELEASE) $(INC_RELEASE) -c src/lib.c -o $(OBJDIR_CONSOLE_RELEASE)/src/lib.o

$(OBJDIR_CONSOLE_RELEASE)/src/main.o: src/main.c
	$(CC) $(CFLAGS_CONSOLE_RELEASE) $(INC_RELEASE) -c src/main.c -o $(OBJDIR_CONSOLE_RELEASE)/src/main.o

$(OBJDIR_CONSOLE_RELEASE)/src/save_load.o: src/save_load.c
	$(CC) $(CFLAGS_CONSOLE_RELEASE) $(INC_RELEASE) -c src/save_load.c -o $(OBJDIR_CONSOLE_RELEASE)/src/save_load.o

clean_release:
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf Release
	rm -rf $(OBJDIR_RELEASE)/src

#.PHONY: before_release after_release clean_release
